# Copyright (c) 2022 PHPER Framework Team
# PHPER is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan
# PSL v2. You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
# KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

name: Publish

on:
  push:
    tags: [ "**" ]

env:
  RUST_LOG: debug
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-D warnings"
  LLVM_CONFIG_PATH: llvm-config-10
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libclang
        run: sudo apt-get install -y llvm-10-dev libclang-10-dev

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-config

      - name: Cargo publish phper-sys
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-sys/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper-build
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-build/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper-macros
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-macros/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper-alloc
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-alloc/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper-test
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-test/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper/Cargo.toml
        continue-on-error: true

      - name: Cargo publish phper-doc
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path phper-doc/Cargo.toml
        continue-on-error: true
